name: simplytics_firebase
description: Implementation of Firebase Analytics and Crashlytics services for Simplytics.
version: 1.0.0+1
author: Andy Chentsov <chentsov@gmail.com>
homepage: https://github.com/andyduke/simplytics/tree/master/packages/simplytics_firebase
repository: https://github.com/andyduke/simplytics
issue_tracker: https://github.com/andyduke/simplytics/issues

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  simplytics: ^1.0.0
  firebase_analytics: ^10.1.0
  firebase_crashlytics: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

