name: simplytics_example
description: Simplytics example.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=2.18.5 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  simplytics:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

